#!/usr/bin/env bash


SESSIONFILE="$HOME/.config/tint2/tint2-sessionfile"
AUTOSTART="$HOME/.config/openbox/autostart"
QUESTION="zenity --question --window-icon=/usr/share/icons/hicolor/256x256/apps/al-hello-logo.png"

# remove itself from autostart
sed -i '/panel-switch/d' $AUTOSTART


## Panel Switch
$QUESTION --title="Panel Switcher" --ok-label="Yes Please!" --cancel-label="No Thanks" --width=450 --height=200 \
--text="<big>Would You Like to Use Tint2\nInstead of Polybar?</big>\n
\nSwitch between them in the menu Preferences>Tint2>Tint2 Chooser"
if (( $? == 1 ));then
  echo "  Staying with polybar: exiting..."
else
  echo "  Enabling tray apps and starting tint2"
  rm -rf $SESSIONFILE
  echo 'nm-applet &' >> $AUTOSTART
  echo 'volumicon &' >> $AUTOSTART
  volumeicon &
  nm-applet &
  al-tint2-session &
fi

#al-hello

exit 0
