#!/usr/bin/env bash

## written by Nathaniel Maia for ArchLabs Minimo  <natemaia10@gmail.com>
##
## any enquiries https://sourceforge.net/projects/archlabs-linux-minimo/

# Remove itself from autostart
if [ -e $HOME/.config/openbox/autostart ]; then
  sed -i '/al-hello/d' $HOME/.config/openbox/autostart
fi

# i found this box somewhere and cannot remember
draw_box(){

#=============#
HORZ="-"
VERT="|"
CORNER_CHAR="+"

MINARGS=4
E_BADARGS=65
#=============#


if [ $# -lt "$MINARGS" ]; then          # If args are less than 4, exit.
    exit $E_BADARGS
fi

# Looking for non digit chars in arguments.
# Probably it could be done better
if echo $@ | tr -d [:blank:] | tr -d [:digit:] | grep . &> /dev/null; then
   exit $E_BADARGS
fi

BOX_HEIGHT=`expr $3 - 1`   #  -1 correction needed because angle char "+"
BOX_WIDTH=`expr $4 - 1`    #+ is a part of both box height and width.
T_ROWS=`tput lines`        #  Define current terminal dimension
T_COLS=`tput cols`         #+ in rows and columns.

if [ $1 -lt 1 ] || [ $1 -gt $T_ROWS ]; then    #  Start checking if arguments
   exit $E_BADARGS                             #+ are correct.
fi
if [ $2 -lt 1 ] || [ $2 -gt $T_COLS ]; then
   exit $E_BADARGS
fi
if [ `expr $1 + $BOX_HEIGHT + 1` -gt $T_ROWS ]; then
   exit $E_BADARGS
fi
if [ `expr $2 + $BOX_WIDTH + 1` -gt $T_COLS ]; then
   exit $E_BADARGS
fi
if [ $3 -lt 1 ] || [ $4 -lt 1 ]; then
   exit $E_BADARGS
fi                                 # End checking arguments.

plot_char(){                       # Function within a function.
   echo -e "\E[${1};${2}H"$3
}

echo -ne "\E[3${5}m"               # Set box frame color, if defined.

# start drawing the box

count=1                                         #  Draw vertical lines using
for (( r=$1; count<=$BOX_HEIGHT; r++)); do      #+ plot_char function.
  plot_char $r $2 $VERT
  let count=count+1
done

count=1
c=`expr $2 + $BOX_WIDTH`
for (( r=$1; count<=$BOX_HEIGHT; r++)); do
  plot_char $r $c $VERT
  let count=count+1
done

count=1                                        #  Draw horizontal lines using
for (( c=$2; count<=$BOX_WIDTH; c++)); do      #+ plot_char function.
  plot_char $1 $c $HORZ
  let count=count+1
done

count=1
r=`expr $1 + $BOX_HEIGHT`
for (( c=$2; count<=$BOX_WIDTH; c++)); do
  plot_char $r $c $HORZ
  let count=count+1
done

plot_char $1 $2 $CORNER_CHAR                   # Draw box angles.
plot_char $1 `expr $2 + $BOX_WIDTH` $CORNER_CHAR
plot_char `expr $1 + $BOX_HEIGHT` $2 $CORNER_CHAR
plot_char `expr $1 + $BOX_HEIGHT` `expr $2 + $BOX_WIDTH` $CORNER_CHAR

tput sgr0 # restore colours
}
# set box size
R=2      # Row
C=6      # Column
H=12     # Height
W=81     # Width
col=1    # Color (red)

# set some paths
BIN="/usr/bin"
MENU="$HOME/.config/openbox/menu.xml"
RC_PATH="$HOME/.config/openbox/rc.xml"
AUTOSTART="$HOME/.config/openbox/autostart"
HELPERS="$HOME/.config/xfce4/helpers.rc"
MIMEAPP="$HOME/.config/mimeapps.list"
CONF_PATH="$HOME/.config"

# determine if using nvidia graphics
NV=$(lspci | grep -i "nvidia")

# determine whether virtual environment
VM=$(dmesg | grep -i "hypervisor")

# string comparison case insesitive matching
yes="y"
no="n"

# colours
b='\E[1;34m'
b_nobold='\E[34m'
red='\E[1;31m'
g='\E[1;32m'
y='\E[1;33m'
reg='\E[0m'

# my thanks to the bunsenlabs guys for this nice little hello art
clear; echo -e "\n\n\n${b}                               _   _ _____ _     _     ___
                              | | | | ____| |   | |   / _ \\
                              | |_| |  _| | |   | |  | | | |
                              |  _  | |___| |___| |__| |_| |
                              |_| |_|_____|_____|_____\___/ \n${reg}"
echo -e "                          Hi${b_nobold} ${USER} ${reg}, Welcome to ArchLabs Linux! ${b_nobold}:)${reg}\n"
draw_box $R $C $H $W $col; sleep 1; read -n1 -rsp $'\n      Press Any Key to Continue...'
clear

printf "\n\n  Would you like to update the system & mirrorlist? (recommended) [y/n]: "
read -r upd

if ! [ "${upd,,}" = "${no,,}" ]; then
  clear; echo -e "\nCurrent mirrorlist backed up to /etc/pacman.d/mirrorlist.backup"
  sleep 1

  sudo cp /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.backup
  sudo reflector --score 120 --fastest 50 --sort rate --save /etc/pacman.d/mirrorlist --verbose
  clear
  sudo pacman -Syyu --noconfirm

  clear; echo -e "\n  You can refresh the mirrorlist anytime with the alias ${b}upmirrors${reg}\n"
  sleep 1; read -n1 -rsp $'\n  Press Any Key to Continue...'
fi



# if not a vm remove virtual utils
if [ -z "${VM}" ]; then
  if [ -e /etc/xdg/autostart/vboxclient.desktop ]; then
    sudo rm -f /etc/xdg/autostart/vboxclient.desktop
  fi

  if (pacman -Q al-virtualbox-guest-modules-lts > /dev/null) ; then
    sudo pacman -Rns al-virtualbox-guest-modules-lts virtualbox-guest-utils --noconfirm
  elif (pacman -Q virtualbox-guest-modules-arch > /dev/null) ; then
    sudo pacman -Rns virtualbox-guest-utils virtualbox-guest-modules-arch --noconfirm
  else
    clear; echo -e "\n  No virtaulbox modules installed"
  fi
fi



# Swapfile
if free | awk '/^Swap:/ {exit !$2}'; then
  clear; echo -e "\n${g}  Swap space found on disk. No setup needed${reg}"
  sleep 1.5

else
  clear; printf "\n  Would you like to setup a swapfile? (required for suspend or sleep) [y/n]: "
  read -r swp

  if [ "${swp,,}" = "${yes,,}" ]; then
    clear; printf "\n  Set a custom size? (defaults to size of system RAM) [y/n]: "
    read -r cswp

    if [ "${cswp,,}" = "${yes,,}" ]; then
      clear; printf "\n  Enter the size of swap wanted eg. [8192M] or [8G] for an 8gb system
  M = Mebibytes, G = Gibibytes (size of system RAM or greater required for sleep/suspend)\n\n\n: "
      read -r size
    fi
  fi
fi




# window manager and session
clear; printf "\n  Pick from additional Window Managers or Desktop Environments?  [y/n]: "
read -r desktop
if ! [ "${desktop,,}" = "${no,,}" ]; then
  clear; printf "\n  Available\n
  1${red})${reg}XFCE  2${red})${reg}i3 gaps  3${red})${reg}Bspwm  4${red})${reg}Awesome\n\n\n: "
  read -r wm

  if [[ $wm == *1* ]] || [[ $wm == *2* ]] || [[ $wm == *3* ]] || [[ $wm == *4* ]]; then
    if [[ $wm == *1* ]]; then
      clear; printf "\n  Want XFCE to be your login session?  [y/n]: "
      read -r xfses
    fi

    if [[ $wm == *2* ]]; then
      if ! [ "${xfses,,}" = "${yes,,}" ]; then
        clear; printf "\n  Want i3 to be your login session?  [y/n]: "
        read -r i3ses
      fi
    fi

    if [ "${xfses,,}" = "${yes,,}" ] || [ "${i3ses,,}" = "${yes,,}" ]; then
      clear; printf "\n  ${red}Remove Openbox${reg}?  [y/n]: "
      read -r rmob
    fi
  fi
fi



## Panel Switch
# openbox wasnt removed
if ! [ "${rmob,,}" = "${yes,,}" ]; then
  clear; printf "\n  Switch to Tint2? (${b}switch anytime in the menu${reg})  [y/n]: "
  read -r panel
  clear; printf "\n  Docks \n\n  1${red})${reg}Plank  2${red})${reg}Docky  3${red})${reg}Cairo\n\n  "
  read -r dock
elif [ "${rmob,,}" = "${yes,,}" ] && [[ $wm == *1* ]]; then  # using xfce and openbox was removed
  clear; printf "\n  Docks \n\n  1${red})${reg}Plank  2${red})${reg}Docky  3${red})${reg}Cairo\n\n  "
  read -r dock
else # openbox was removed but xfce wasnt picked
  echo -e "\n  Openbox will be removed"
fi

# switch panel
if [ "${panel,,}" = "${yes,,}" ]; then
  if ! (grep "default.tint2rc" $CONF_PATH/tint2/tint2-sessionfile) > /dev/null 2>&1; then
    echo "/home/$USER/.config/tint2/default.tint2rc" > $CONF_PATH/tint2/tint2-sessionfile
  fi
  if ! (grep "volumeicon" $AUTOSTART) > /dev/null 2>&1; then
    echo "sleep 2; volumeicon &" >> $AUTOSTART
  fi
  if ! (grep "nm-applet" $AUTOSTART) > /dev/null 2>&1; then
    echo "sleep 2; nm-applet &" >> $AUTOSTART
  fi
  if ! (pgrep -x volumeicon </dev/null) > /dev/null 2>&1; then
    volumeicon &
  fi
  if ! (pgrep -x nm-applet </dev/null) > /dev/null 2>&1; then
    nm-applet &
  fi
  al-tint2-session > /dev/null 2>&1
fi




clear; printf "\n  Select Applications to Install?  [y/n]: "
read -r defaults

if ! [ "${defaults,,}" = "${no,,}" ]; then

  clear; echo -e "\n\n  During the following you will be asked to pick applications you like,
  just enter the corresponding number of the application(s) you want installed
  (${red}unless told otherwise any combination of choices can be made${reg})"

  sleep 2
  read -n1 -rsp $'\n\n  Press Any Key to Continue...'


  clear; printf "\n  Web Browsers (Firefox is default)\n
  1${red})${reg}Chrome  2${red})${reg}Chromium  3${red})${reg}Opera\n\n\n: "
  read -r bwsr
  if [[ $bwsr == *1* ]] || [[ $bwsr == *2* ]] || [[ $bwsr == *3* ]]; then
    if [[ $bwsr == *1* ]] || [[ $bwsr == *2* ]]; then
      clear; printf "\n  Install google talk plugin?  [y/n]: "
      read -r tlk
    fi

    clear; printf "\n  Uninstall Firefox?  [y/n]: "
    read -r remove_firefox
    if ! [[ $bwsr == "1" ]] || [ "${remove_firefox,,}" = "${no,,}" ]; then
      clear; printf "\n  Install flash plugin?  [y/n]: "
      read -r flsh
    fi

    clear; echo -e "\n  ArchLabs provides a local homepage ${b}~/.ArchLabs-homepage/index.html${reg}
  This can be opened with any browser and set as the homepage if you like\n\n\n"
    read -n1 -rsp $'  Press Any Key to continue...\n'

  else
    clear; printf "\n  Install flash plugin?  [y/n]: "
    read -r flsh
  fi


  if ! [[ $wm == *1* ]]; then
    clear; printf "\n  Text Editors (Geany is default)\n
  1${red})${reg}Atom  2${red})${reg}Sublime  3${red})${reg}Mousepad\n\n\n: "
    read -r edit
  else
    clear; printf "\n  Text Editors (Geany and Mousepad are default)\n
  1${red})${reg}Atom  2${red})${reg}Sublime\n\n\n: "
    read -r edit
  fi
  if [[ $edit == *1* ]] || [[ $edit == *2* ]] || [[ $edit == *3* ]]; then
    clear; printf "\n  Uninstall Geany?  [y/n]: "
    read -r redit
  fi


  if ! [[ $wm == *1* ]]; then
    clear; printf "\n  Terminal Emulators (Termite is the default)\n
  1${red})${reg}Tilix  2${red})${reg}Terminator  3${red})${reg}Urxvt  4${red})${reg}Tilda  5${red})${reg}Xfce4 terminal\n\n\n: "
    read -r term
  else
    clear; printf "\n  Terminal Emulators (Termite is the default)\n
  1${red})${reg}Tilix  2${red})${reg}Terminator  3${red})${reg}Urxvt  4${red})${reg}Tilda\n\n\n: "
    read -r term
  fi
  if [[ $term == *3* ]]; then
    clear; echo -e "\n  You can copy paste in urxvt with ${b}[Alt + c] [Alt + v]${reg}\n\n\n"
    read -n1 -rsp $'  Press Any Key to continue...\n'
  fi


  clear; printf "\n  Music Players (Audacious is the default)\n
  1${red})${reg}Spotify  2${red})${reg}Nicotine+  3${red})${reg}Lollypop  4${red})${reg}Rythmbox  5${red})${reg}Clementine\n\n\n: "
  read -r musc
  if [[ $musc == *3* ]] || [[ $musc == *4* ]] || [[ $musc == *5* ]]; then
    clear; printf "\n  Uninstall Audacious?  [y/n]: "
    read -r rmusc
  fi

  clear; printf "\n  MPV is ArchLabs Default Video Player, install VLC instead? (120M) [y/n]: "
  read -r vlc

  # if openbox wasnt removed and not using xfce we can change file manager
  clear; printf "\n  File Managers (Thunar is default)\n
  1${red})${reg}PCmanFM  2${red})${reg}Nautilus  3${red})${reg}Nemo\n\n\n: "
    read -r file
    if ! [[ $wm == *1* ]]; then
      if [[ $file == *1* ]] || [[ $file == *2* ]] || [[ $file == *3* ]]; then
        clear; printf "\n  Uninstall Thunar?  [y/n]: "
        read -r rmfile
      fi
    fi

  clear; printf "\n  Screen Capture\n
  1${red})${reg}SSR  2${red})${reg}OBS  2${red})${reg}Guvcview  4${red})${reg}Peek\n\n\n: "
  read -r cap

  clear; printf "\n  Video Editors\n
  1${red})${reg}Kdenlive  2${red})${reg}Openshot  3${red})${reg}Lightworks\n\n\n: "
  read -r vid

  clear; printf "\n  Image Editors\n
  1${red})${reg}Gimp  2${red})${reg}Inkscape  3${red})${reg}Krita  4${red})${reg}Pinta\n\n\n: "
  read -r img

  clear; printf "\n  Office Suites\n
  1${red})${reg}Libre Office  2${red})${reg}Abiword  3${red})${reg}Caligra\n\n\n: "
  read -r off

  clear; printf "\n  USB Burners\n
  1${red})${reg}Etcher  2${red})${reg}Mintstick  3${red})${reg}Unetbootin  4${red})${reg}Etcher-cli\n\n\n: "
  read -r usb

  clear; printf "\n  Mail Clients\n
  1${red})${reg}Thunderbird  2${red})${reg}Geary  3${red})${reg}Evolution  4${red})${reg}Mutt\n\n\n: "
  read -r mail

  clear; printf "\n  Chat and IRC\n
  1${red})${reg}Hexchat  2${red})${reg}Pidgin  3${red})${reg}Weechat  4${red})${reg}Irssi\n\n\n: "
  read -r irc

  clear; printf "\n  Torrent Clients\n
  1${red})${reg}Deluge  2${red})${reg}Transmission  3${red})${reg}qBittorrent\n\n\n: "
  read -r tor

  clear; printf "\n  Color Selector tools\n
  1${red})${reg}Gpick  2${red})${reg}Gcolor2\n\n\n: "
  read -r pick

  clear; printf "\n  Additional terminal applications\n
  1${red})${reg}Mpd & Ncmpcpp  2${red})${reg}Cava  3${red})${reg}S-tui\n\n\n: "
  read -r ter

  # if not using xfce we can pick a few xfce apps
  if ! [[ $wm == *1* ]]; then
    clear; printf "\n  Disc Burners\n
  1${red})${reg}Xfburn  2${red})${reg}Simpleburn  3${red})${reg}K3b\n\n\n: "
    read -r brn

    clear; printf "\n  XFCE notifications?  [y/n]: "
    read -r notify

    clear; printf "\n  XFCE Power Manager?  [y/n]: "
    read -r pwr

    # installing pamac if XFCE was chosen regardless
    clear; printf "\n  Pamac Package Manager? (default is Pacli) [y/n]: "
    read -r pac
  fi

  clear; printf "\n  Gnome Disk Utility & System Monitor  [y/n]: "
  read -r gnm

  clear; printf "\n  Catfish File Search  [y/n]: "
  read -r sch

  clear; printf "\n  Steam  [y/n]: "
  read -r steam

  clear; printf "\n  Dropbox  [y/n]: "
  read -r dbox

  clear; printf "\n  Some of our favorite fonts?  [y/n]: "
  read -r fnt

  clear; printf "\n  Additional icon patched fonts? (260M) [y/n]: "
  read -r nfnt

  clear; printf "\n  Install oomox for making GTK themes?  [y/n]: "
  read -r omox
fi
# end of default app selection




clear; echo -e "${g}#######################################################################################
#######                           Starting Install                              #######
#######################################################################################${reg}"
sleep 1; clear


sudo pacman -S base-devel --needed --noconfirm


# if openbox wasnt removed
if ! [ "${rmob,,}" = "${yes,,}" ]; then

  # Setup menu generator and switcher scripts
  if ! (pacman -Q obmenu-generator perl-data-dump gtk2-perl perl-linux-desktopfiles) > /dev/null 2>&1; then
    yaourt -S obmenu-generator perl-data-dump gtk2-perl perl-linux-desktopfiles --noconfirm --needed
  fi
  if ! (grep "genmenu" $MENU) > /dev/null 2>&1; then
    sed -i '/al-kb-pipemenu/ a\
    <item label="Switch Menu">\
      <action name="Execute">\
        <command>genmenu</command>\
      </action>\
    </item>' $MENU
  fi
  openbox --reconfigure
else
  rm -rf $CONF_PATH/{ob*,openbox} # Openbox was removed
fi




## Start default app install
if ! [ "${defaults,,}" = "${no,,}" ]; then

  # Chat and IRC
  if [[ $irc == *1* ]] || [[ $irc == *2* ]] || [[ $irc == *3* ]] || [[ $irc == *4* ]]; then
    if [[ $irc == *1* ]]; then
      sudo pacman -S hexchat --noconfirm --needed
    fi
    if [[ $irc == *2* ]]; then
      sudo pacman -S pidgin --noconfirm --needed
    fi
    if [[ $irc == *3* ]]; then
      sudo pacman -S weechat --noconfirm --needed
    fi
    if [[ $irc == *4* ]]; then
      sudo pacman -S irssi --noconfirm --needed
    fi
  fi



  ## Browser
  if [[ $bwsr == *1* ]] || [[ $bwsr == *2* ]] || [[ $bwsr == *3* ]]; then
    if [[ $bwsr == *1* ]]; then
      if [ "${tlk,,}" = "${yes,,}" ]; then
        yaourt -S google-chrome google-talkplugin --noconfirm --needed
      else
        yaourt -S google-chrome --noconfirm --needed
      fi
    fi

    if [[ $bwsr == *2* ]]; then
    	sudo pacman -S chromium --noconfirm --needed
    fi

    if [[ $bwsr == *3* ]]; then
    	sudo pacman -S opera --noconfirm --needed
    fi

    if [ "${remove_firefox,,}" = "${yes,,}" ]; then
      sudo pacman -Rn firefox --noconfirm
      rm -rf $HOME/.mozilla
      if [[ $bwsr == *1* ]]; then
        echo '[Desktop Entry]
NoDisplay=true
Version=1.0
Encoding=UTF-8
Type=X-XFCE-Helper
X-XFCE-Category=WebBrowser
X-XFCE-CommandsWithParameter=google-chrome-stable "%s"
Icon=google-chrome
Name=Google Chrome
X-XFCE-Commands=google-chrome-stable' > $HOME/.local/share/xfce4/helpers/custom-WebBrowser.desktop
        sed -i 's/firefox/custom-WebBrowser/g' $HELPERS $CONF_PATH/xfce4/al-xfce-configs/helpers.rc
      fi

      if [[ $bwsr == *2* ]]; then
        sed -i 's/firefox/chromium/g' $HELPERS $CONF_PATH/xfce4/al-xfce-configs/helpers.rc
      fi

      if [[ $bwsr == *3* ]]; then
        sed -i 's/firefox/opera/g' $HELPERS $CONF_PATH/xfce4/al-xfce-configs/helpers.rc
      fi
    fi
  fi



  # flash
  if [ "${flsh,,}" = "${yes,,}" ]; then
    sudo pacman -S flashplugin --noconfirm --needed
  fi



  # text editors
  if [[ $edit == *1* ]] || [[ $edit == *2* ]] || [[ $edit == *3* ]]; then
    if [[ $edit == *1* ]]; then
      sudo pacman -S atom --noconfirm --needed
      sed -i 's/geany/atom/g' $MIMEAPP $MENU $RC_PATH
      sudo sed -i 's/TEXT_EDITOR="geany"/TEXT_EDITOR="atom"/g' /usr/bin/al-open
    fi

    if [[ $edit == *2* ]]; then
      yaourt -S sublime-text-dev --noconfirm --needed
      sed -i 's/geany/sublime_text_3/g' $MIMEAPP
      sed -i 's/geany/subl3/g' $RC_PATH $MENU
      sudo sed -i 's/TEXT_EDITOR="geany"/TEXT_EDITOR="subl3"/g' /usr/bin/al-open
    fi

    if [[ $edit == *3* ]]; then
      if ! [[ $wm == *1* ]]; then
        sudo pacman -S mousepad --noconfirm --needed
        sed -i 's/geany/mousepad/g' $MIMEAPP $MENU $RC_PATH
        sudo sed -i 's/TEXT_EDITOR="geany"/TEXT_EDITOR="mousepad"/g' /usr/bin/al-open
      fi
    fi

    if [ "${redit,,}" = "${yes,,}" ]; then
      sudo pacman -Rn geany --noconfirm
      rm -rf $CONF_PATH/geany
    fi
  fi



  # terminal emulators
  if [[ $term == *1* ]] || [[ $term == *2* ]] || [[ $term == *3* ]] || [[ $term == *4* ]] || [[ $term == *5* ]]; then
    if [[ $term == *1* ]]; then
      yaourt -S tilix --noconfirm --needed
      if [ -e $HOME/.local/share/xfce4/helpers/custom-TerminalEmulator.desktop ]; then
        sed -i 's/Termite/Tilix/g' $HOME/.local/share/xfce4/helpers/custom-TerminalEmulator.desktop
        sed -i 's/termite/tilix/g' $HOME/.local/share/xfce4/helpers/custom-TerminalEmulator.desktop
      fi
    fi

    if [[ $term == *2* ]]; then
      sudo pacman -S terminator --noconfirm --needed
      sed -i 's/custom-TerminalEmulator/terminator/g' $HELPERS
    fi

    if [[ $term == *3* ]]; then
      sudo pacman -S rxvt-unicode urxvt-perls xclip --noconfirm --needed
      sed -i 's/custom-TerminalEmulator/urxvt/g' $HELPERS
      if ! [ "${rmob,,}" = "${yes,,}" ]; then
        if ! (grep "xclip" $AUTOSTART) > /dev/null 2>&1; then
          echo 'sleep 3; xclip &' >> $AUTOSTART
        fi
      fi
    fi

    if [[ $term == *4* ]]; then
      sudo pacman -S tilda --noconfirm --needed
      if [ -e $HOME/.local/share/xfce4/helpers/custom-TerminalEmulator.desktop ]; then
        sed -i 's/Termite/Tilda/g' $HOME/.local/share/xfce4/helpers/custom-TerminalEmulator.desktop
        sed -i 's/termite/tilda/g' $HOME/.local/share/xfce4/helpers/custom-TerminalEmulator.desktop
      fi
    fi

    if ! [[ $wm == *1* ]]; then
      if [[ $term == *5* ]]; then
        sudo pacman -S xfce4-terminal --noconfirm --needed
        sed -i 's/custom-TerminalEmulator/xfce4-terminal/g' $HELPERS
      fi
    fi
  fi



  # file manager
  if [[ $file == *1* ]] || [[ $file == *2* ]] || [[ $file == *3* ]]; then
    if [[ $file == *1* ]]; then
      sudo pacman -S pcmanfm --noconfirm --needed
      sed -i 's/Thunar-folder-handler/pcmanfm/g' $MIMEAPP
      sed -i 's/Thunar/pcmanfm/g' $HELPERS
      if ! [ "${rmob,,}" = "${yes,,}" ]; then
        sed -i 's/thunar --daemon/pcmanfm -d/g' $AUTOSTART
        sed -i 's/thunar/pcmanfm/g' $MENU
      fi
    fi

    if [[ $file == *2* ]]; then
      sudo pacman -S nautilus nautilus-open-terminal nautilus-terminal --noconfirm --needed
      sed -i 's/Thunar-folder-handler/org.gnome.Nautilus/g' $MIMEAPP
      sed -i 's/Thunar/nautilus/g' $HELPERS
      if ! [ "${rmob,,}" = "${yes,,}" ]; then
        sed -i '/thunar/d' $AUTOSTART
        sed -i 's/thunar/nautilus/g' $MENU
      fi
    fi

    if [[ $file == *3* ]]; then
      sudo pacman -S nemo nemo-fileroller nemo-preview nemo-share --noconfirm --needed
      gsettings set org.nemo.desktop show-desktop-icons false
      gsettings set org.cinnamon.desktop.default-applications.terminal exec termite
      sed -i 's/Thunar-folder-handler/org.gnome.Nautilus/g' $MIMEAPP
      sed -i 's/Thunar/nemo/g' $HELPERS
      if ! [ "${rmob,,}" = "${yes,,}" ]; then
        sed -i '/thunar/d' $AUTOSTART
        sed -i 's/thunar/nemo/g' $MENU
      fi
    fi

    if ! [[ $wm == *1* ]]; then
      if [ "${rmfile,,}" = "${yes,,}" ]; then
        sudo pacman -Rn thunar --noconfirm
        rm -rf $CONF_PATH/Thunar
      fi
    fi
  fi



  # operations if not choosing xfce
  if ! [[ $wm == *1* ]]; then

    # disc burner
    if [[ $brn == *1* ]] || [[ $brn == *2* ]] || [[ $brn == *3* ]]; then
      if [[ $brn == *1* ]]; then
        sudo pacman -S xfburn --noconfirm --needed
      fi
      if [[ $brn == *2* ]]; then
        yaourt -S simpleburn --noconfirm --needed
      fi
      if [[ $brn == *3* ]]; then
        sudo pacman -S k3b --noconfirm --needed
      fi
    fi



    # power manager
    if [ "${pwr,,}" = "${yes,,}" ]; then
      sudo pacman -S xfce4-power-manager --noconfirm --needed
      if ! [ "${rmob,,}" = "${yes,,}" ]; then
        if ! (grep "power-manager" $AUTOSTART) > /dev/null 2>&1; then
          echo "xfce4-power-manager &" >> $AUTOSTART
        fi
      fi
    fi



    # notifications
    if [ "${notify,,}" = "${yes,,}" ]; then
      sudo pacman -S xfce4-notifyd --noconfirm --needed
      if ! [ "${rmob,,}" = "${yes,,}" ]; then
        if ! (grep "notifyd" $AUTOSTART) > /dev/null 2>&1; then
          echo "xfce4-notifyd &" >> $AUTOSTART
        fi
      fi
    fi



    # pamac & polkit
    if [ "${pac,,}" = "${yes,,}" ]; then
      yaourt -S pamac-aur --noconfirm --needed

      if ! [ "${rmob,,}" = "${yes,,}" ]; then
        if (grep "pacli" $MENU) > /dev/null 2>&1; then
          sed -i 's/termite --exec=pacli/pamac-manager/g' $MENU
        fi

        if ! (grep "pamac-tray" $AUTOSTART) > /dev/null 2>&1; then
          echo  "sleep 2; pamac-tray &" >> $AUTOSTART
        fi
      fi

      if [ -e $CONF_PATH/polybar/modules.conf ]; then
        sed -i 's/termite --exec=pacli/pamac-manager/g' $CONF_PATH/polybar/modules.conf
      fi
    fi
  fi



  # usb image writers
  if [[ $usb == *1* ]] || [[ $usb == *2* ]] || [[ $usb == *3* ]] || [[ $usb == *4* ]]; then
    if [[ $usb == *1* ]]; then
      yaourt -S etcher --noconfirm --needed
    fi

    if [[ $usb == *2* ]]; then
      yaourt -S mintstick-git --noconfirm --needed
    fi

    if [[ $usb == *3* ]]; then
      sudo pacman -S unetbootin --noconfirm --needed
    fi

    if [[ $usb = *4* ]]; then
      yaourt -S etcher-cli --noconfirm --needed
    fi
  fi



  # music
  if [[ $musc == *1* ]] || [[ $musc == *2* ]] || [[ $musc == *3* ]] || [[ $musc == *4* ]] || [[ $musc == *5* ]]; then
    if [[ $musc == *1* ]]; then
      yaourt -S spotify --noconfirm --needed
    fi

    if [[ $musc == *2* ]]; then
      yaourt -S nicotine+ --noconfirm --needed
    fi

    if [[ $musc == *3* ]]; then
      yaourt -S lollypop --noconfirm --needed
    fi

    if [[ $musc == *4* ]]; then
      yaourt -S rythmbox --noconfirm --needed
    fi

    if [[ $musc == *5* ]]; then
      sudo pacman -S clementine qt5ct qt5-styleplugins --noconfirm --needed
    fi

    if [ "${rmusc,,}" = "${yes,,}" ]; then
      sudo pacman -Rn audacious audacious-plugins --noconfirm
      if ! [ "${rmob,,}" = "${yes,,}" ]; then
        if [[ $musc == *3* ]]; then
          sed -i 's/audacious/lollypop/g' $MENU $RC_PATH
          sudo sed -i 's/MUSIC_PLAYER="audacious"/MUSIC_PLAYER="lollypop"/g' /usr/bin/al-open
        fi

        if [[ $musc == *4* ]]; then
          sed -i 's/audacious/rythmbox/g' $MENU $RC_PATH
          sudo sed -i 's/MUSIC_PLAYER="audacious"/MUSIC_PLAYER="rythmbox"/g' /usr/bin/al-open
        fi

        if [[ $musc == *5* ]]; then
          sed -i 's/audacious/clementine/g' $MENU $RC_PATH
          sudo sed -i 's/MUSIC_PLAYER="audacious"/MUSIC_PLAYER="clementine"/g' /usr/bin/al-open
        fi
      fi
    fi
  fi



  # vlc
  if [ "${vlc,,}" = "${yes,,}" ]; then
    sudo pacman -S vlc qt4 --noconfirm --needed
    sudo pacman -Rn mpv --noconfirm
    sed -i 's/mpv --player-operation-mode=pseudo-gui/vlc/g' $MENU
  else
    sudo pacman -S a52dec autofs faac faad2 flac lame libdca libdv libmad libmpeg2 --noconfirm --needed
    sudo pacman -S libtheora libvorbis libxv wavpack x264 libdvdcss dvd+rw-tools dvdauthor dvgrab --needed --noconfirm
  fi



  # image editor
  if [[ $img == *1* ]] || [[ $img == *2* ]] || [[ $img == *3* ]] || [[ $img == *4* ]]; then
    if [[ $img == *1* ]]; then
      sudo pacman -S gimp --noconfirm --needed
    fi

    if [[ $img == *2* ]]; then
      sudo pacman -S inkscape --noconfirm --needed
    fi

    if [[ $img == *3* ]]; then
      sudo pacman -S krita --noconfirm --needed
    fi

    if [[ $img == *4* ]]; then
      sudo pacman -S pinta --noconfirm --needed
    fi
  fi



  # screen capture
  if [[ $cap == *1* ]] || [[ $cap == *2* ]] || [[ $cap == *3* ]]; then
    if [[ $cap == *1* ]]; then
      sudo pacman -S simplescreenrecorder --noconfirm --needed
    fi

    if [[ $cap == *2* ]]; then
      sudo pacman -S obs-studio --noconfirm --needed
    fi

    if [[ $cap == *3* ]]; then
      yaourt -S guvcview --noconfirm --needed
    fi

    if [[ $cap == *4* ]]; then
      yaourt -S peek --noconfirm --needed
    fi
  fi



  # video editor
  if [[ $vid == *1* ]] || [[ $vid == *2* ]] || [[ $vid == *3* ]]; then
    if [[ $vid == *1* ]]; then
      sudo pacman -S kdenlive kdebase-runtime dvdauthor frei0r-plugins breeze breeze-icons --noconfirm --needed

      if ! [ "${rmob,,}" = "${yes,,}" ]; then
        if ! (grep "QT_QPA_PLATFORMTHEME" $CONF_PATH/openbox/environment) > /dev/null 2>&1; then
          echo "QT_QPA_PLATFORMTHEME=qt5ct" >> $CONF_PATH/openbox/environment
        fi
      fi

      if ! (grep "QT_STYLE_OVERRIDE" $HOME/.xsessionrc) > /dev/null 2>&1; then
        echo "export QT_STYLE_OVERRIDE=GTK+" >> $HOME/.xsessionrc
      fi

      mkdir -p $CONF_PATH/qt5ct
      echo "[Appearance]
color_scheme_path=
custom_palette=false
icon_theme=breeze
style=Breeze

[Interface]
activate_item_on_single_click=1
buttonbox_layout=0
cursor_flash_time=1000
dialog_buttons_have_icons=0
double_click_interval=400
gui_effects=General
menus_have_icons=true
stylesheets=@Invalid()
toolbutton_style=4
wheel_scroll_lines=3" > $CONF_PATH/qt5ct/qt5ct.conf
    fi

    if [[ $vid == *2* ]]; then
      sudo pacman -S openshot --noconfirm --needed
    fi

    if [[ $vid == *3* ]]; then
      yaourt -S lwks --noconfirm --needed
    fi
  fi



  # office
  if [[ $off == *1* ]] || [[ $off == *2* ]] || [[ $off == *3* ]]; then
    if [[ $off == *1* ]]; then
      sudo pacman -S libreoffice-fresh --noconfirm --needed
    fi

    if [[ $off == *2* ]]; then
      sudo pacman -S abiword --noconfirm --needed
    fi

    if [[ $off == *3* ]]; then
      sudo pacman -S calligra --noconfirm --needed
    fi
  fi



  # mail client
  if [[ $mail == *1* ]] || [[ $mail == *2* ]] || [[ $mail == *3* ]] || [[ $mail == *4* ]]; then
    if [[ $mail == *1* ]]; then
      sudo pacman -S thunderbird --noconfirm --needed
      if ! (grep "MailReader" $HELPERS) > /dev/null 2>&1; then
        echo "MailReader=thunderbird" >> $HELPERS
      fi
    fi

    if [[ $mail == *2* ]]; then
      sudo pacman -S  geary --noconfirm --needed
      if ! (grep "MailReader" $HELPERS) > /dev/null 2>&1; then
        echo "MailReader=geary" >> $HELPERS
      fi
    fi

    if [[ $mail == *3* ]]; then
      sudo pacman -S evolution --noconfirm --needed
      if ! (grep "MailReader" $HELPERS) > /dev/null 2>&1; then
        echo "MailReader=evolution" >> $HELPERS
      fi
    fi

    if [[ $mail == *4* ]]; then
      sudo pacman -S mutt --noconfirm --needed
    fi
  fi



  # torrent client
  if [[ $tor == *1* ]] || [[ $tor == *2* ]] || [[ $tor == *3* ]]; then
    if [[ $tor == *1* ]]; then
      sudo pacman -S deluge --noconfirm --needed
    fi

    if [[ $tor == *2* ]]; then
      sudo pacman -S transmission-gtk --noconfirm --needed
    fi

    if [[ $tor == *3* ]]; then
      sudo pacman -S qbittorrent --noconfirm --needed
    fi
  fi



  # color picker
  if [[ $pick == *1* ]] || [[ $pick == *2* ]]; then
    if [[ $pick == *1* ]]; then
      sudo pacman -S gpick --noconfirm --needed
    fi

    if [[ $pick == *2* ]]; then
      sudo pacman -S gcolor2 --noconfirm --needed
    fi
  fi



  # dropbox
  if [ "${dbox,,}" = "${yes,,}" ]; then
    yaourt -S dropbox --noconfirm --needed
  fi



  # steam
  if [ "${steam,,}" = "${yes,,}" ]; then
    sudo pacman -S steam steam-native-runtime --noconfirm --needed
    yaourt -S ttf-ms-fonts --noconfirm --needed

    if ! [ "${rmob,,}" = "${yes,,}" ]; then
      if ! (grep "steam" $AUTOSTART) > /dev/null 2>&1; then
        echo "sleep 2; steam -silent &" >> $AUTOSTART
      fi
    fi
  fi


  # terminal apps
  if [[ $ter == *1* ]] || [[ $ter == *2* ]] || [[ $ter == *3* ]]; then
    if [[ $ter == *1* ]]; then
      sudo pacman -S mpd ncmpcpp --noconfirm --needed
    fi

    if [[ $ter == *2* ]]; then
      yaourt -S cava --noconfirm --needed
    fi

    if [[ $ter == *3* ]]; then
      yaourt -S s-tui python2-psutil --noconfirm --needed
    fi
  fi


  # oomox
  if [ "${omox,,}" = "${yes,,}" ]; then
    yaourt -S oomox --noconfirm --needed
  fi

  # fonts
  if [ "${fnt,,}" = "${yes,,}" ]; then
    yaourt -S ttf-hack ttf-anonymous-pro ttf-font-awesome ttf-fira-code ttf-material-icons --noconfirm
  fi

  # nerd fonts
  if [ "${nfnt,,}" = "${yes,,}" ]; then
    yaourt -S nerd-fonts-complete --noconfirm --needed
  fi

  # catfish
  if [ "${sch,,}" = "${yes,,}" ]; then
    sudo pacman -S catfish --noconfirm --needed
  fi

  # gnome disk utility and system monitor
  if [ "${gnm,,}" = "${yes,,}" ]; then
    sudo pacman -S gnome-disk-utility gnome-system-monitor --noconfirm --needed
  fi
fi



# dock
if [[ $dock == *1* ]] || [[ $dock == *2* ]] || [[ $dock == *3* ]]; then
  if [[ $dock == *1* ]]; then
    sudo pacman -S plank --noconfirm --needed

    if ! [ "${rmob,,}" = "${yes,,}" ]; then
      if ! (grep "plank" $AUTOSTART) > /dev/null 2>&1; then
        echo "sleep 2; plank &" >> $AUTOSTART
      fi
    fi
  fi

  if [[ $dock == *2* ]]; then
    sudo pacman -S docky --noconfirm --needed

    if ! [ "${rmob,,}" = "${yes,,}" ]; then
      if ! (grep "docky" $AUTOSTART) > /dev/null 2>&1; then
        echo "sleep 2; docky &" >> $AUTOSTART
      fi
    fi
  fi

  if [[ $dock == *3* ]]; then
    sudo pacman -S cairo-dock cairo-dock-plug-ins --noconfirm --needed

    if ! [ "${rmob,,}" = "${yes,,}" ]; then
      if ! (grep "cairo-dock" $AUTOSTART) > /dev/null 2>&1; then
        echo "sleep 2; cairo-dock &" >> $AUTOSTART
      fi
    fi
  fi
fi





# Window Manager Setup
if [[ $wm == *1* ]] || [[ $wm == *2* ]] || [[ $wm == *3* ]] || [[ $wm == *4* ]]; then

  # XFCE
  if [[ $wm == *1* ]]; then
    sudo pacman -S xfce4 xfce4-goodies xfce4-pulseaudio-plugin --noconfirm --needed
    yaourt -S pamac-aur --noconfirm --needed

    # copy configs
    if [ -d $CONF_PATH/xfce4/al-xfce-configs ]; then # copy configs
      mv -f $CONF_PATH/xfce4/al-xfce-configs/.gtkrc-2.0 $HOME/.gtkrc-2.0
      cp -r $CONF_PATH/xfce4/al-xfce-configs/* $CONF_PATH/xfce4/
      rm -rf $CONF_PATH/xfce4/al-xfce-configs
    fi
    # fix desktop icons
    xfconf-query -c xfce4-desktop -v --create -p /desktop-icons/style -t int -s 0  # fix desktop icons

    # ensure pamac is setup properly for openbox
    if ! [ "${rmob,,}" = "${yes,,}" ]; then
      if (grep "pacli" $MENU) > /dev/null 2>&1; then
        sed -i 's/termite --exec=pacli/pamac-manager/g' $MENU
      fi

      if ! (grep "pamac-tray" $AUTOSTART) > /dev/null 2>&1; then
        echo  "sleep 2; pamac-tray &" >> $AUTOSTART
      fi
    fi

    # ensure pamac is setup properly for polybar update script
    if [ -e $CONF_PATH/polybar/modules.conf ]; then
      sed -i 's/termite --exec=pacli/pamac-manager/g' $CONF_PATH/polybar/modules.conf
    fi
  else
      rm -rf $CONF_PATH/xfce4/al-xfce-configs
  fi

  # I3 Gaps
  if [[ $wm == *2* ]]; then
  	yaourt -S i3-gaps i3status --noconfirm --needed
  else
    rm -rf $CONF_PATH/i3
  fi

  # BSPWM
  if [[ $wm == *3* ]]; then
    sudo pacman -S bspwm sxhkd --noconfirm --needed
  else
    rm -rf $CONF_PATH/{bspwm,sxhkd}
  fi

  # Awesome WM
  if [[ $wm == *4* ]]; then
    sudo pacman -S awesome --noconfirm --needed
    mkdir -p $CONF_PATH/awesome/
    cp /etc/xdg/awesome/rc.lua $CONF_PATH/awesome/
  fi

  # Remove openbox
  if [ "${rmob,,}" = "${yes,,}" ]; then
    sudo pacman -Rn openbox oblogout obconf archlabs-ob-autostart archlabs-obkey archlabs-opensnap lxappearance-obconf --noconfirm
    rm -rf $CONF_PATH/{openbox,tint2,obmenu-generator,ob-autostart}
  fi

  # set session
  if [ "${xfses,,}" = "${yes,,}" ]; then
    sed -i 's/custom-TerminalEmulator/xfce4-terminal/g' $HELPERS
    sudo sed -i '/user-session=/ c\
user-session=xfce' /etc/lightdm/lightdm.conf
    sudo sed -i '/autologin-session=/ c\
autologin-session=xfce' /etc/lightdm/lightdm.conf
  elif [ "${i3ses,,}" = "${yes,,}" ]; then
    sudo sed -i '/user-session=/ c\
user-session=i3' /etc/lightdm/lightdm.conf
    sudo sed -i '/autologin-session=/ c\
autologin-session=i3' /etc/lightdm/lightdm.conf
  else
    echo "Session not changed"
  fi

else
  echo -e "\nNo WMs or DEs Chosen"
fi





# Swapfile setup
if [ "${swp,,}" = "${yes,,}" ]; then
  if [ "${cswp,,}" = "${yes,,}" ]; then # set custom size
    if [ -n "$size" ]; then
      if [[ $size == *G ]] || [[ $size == *M ]]; then # ensure the $size ends with G or M
        sudo fallocate -l $size /swapfile
        sudo chmod 600 /swapfile
        sudo mkswap /swapfile
        sudo swapon /swapfile
        echo -e "\n  Appending to /ect/fstab\n"
        echo "/swapfile                                 none           swap    defaults 0 0" | sudo tee -a /etc/fstab
      else
        clear; echo -e "\n  Wrong formatting"
      fi

    else
      clear; echo -e "\n  No size entered"
    fi

  else
    # Create a string of the users total M + 50M
    totalM=$(free --mega | awk '/^Mem:/{print $2}') ; totalM=$(($totalM + 50)) ; totalM="${totalM}M"
    sudo fallocate -l $totalM /swapfile
    sudo chmod 600 /swapfile
    sudo mkswap /swapfile
    sudo swapon /swapfile
    echo -e "\n  Appending to /ect/fstab\n"
    echo "/swapfile                                 none           swap    defaults 0 0" | sudo tee -a /etc/fstab
    sleep 1
  fi
fi




if ! [ -z "${NV}" ]; then
  clear; printf "\n  ${g}Nvidia Graphics Detected.${reg}\n\n  Want nvidia drivers installed?  [y/n]: "
  read -r nvd
fi


# nvidia drivers
if [ "${nvd,,}" = "${yes,,}" ]; then
  if [[ $wm == *2* ]] && [ "${i3ses,,}" = "${yes,,}" ]; then # if we are logging in to i3 we need to set it up is autostart
    if ! (grep "nvidia-easy-install" $CONF_PATH/i3/config) > /dev/null 2>&1; then
      echo 'exec --no-startup-id sleep 5; termite --exec=/usr/bin/nvidia-easy-install' >> $CONF_PATH/i3/config
    fi

  else
    if ! [ -e /etc/xdg/autostart/nvidia-easy-install.desktop ]; then
      echo '[Desktop Entry]
Version=1.0
Name=Nvidia Installer
Exec=termite "--exec=/usr/bin/nvidia-easy-install"
Terminal=false
Type=Application
Categories=Utility;
StartupNotify=true
X-GNOME-Autostart-enabled=true' | sudo tee -a /etc/xdg/autostart/nvidia-easy-install.desktop
      clear
    fi
  fi

  clear; echo -e "\n${g}  Next boot you will be promted with Nvidia Driver Installation${reg}"
  sleep 2

else
  if [ -e /etc/xdg/autostart/nvidia-easy-install.desktop ]; then
    sudo rm -f /etc/xdg/autostart/nvidia-easy-install.desktop
  fi
fi

read -n1 -rsp $'\n  Setup Complete!!\n\n\n  Press Any Key to Reboot or Ctrl + c to exit...'

systemctl reboot

exit 0
